### ISSUE TITLE
Creazione del pannello admin come suggerito da @Porchetta

### ISSUE THREAD

**Issue by Azzeccagarbugli** [Azzeccagarbugli/UnicamEat#11]
Implementare un pannello in stile _BotFather_ per le impostazioni del pannello admin, accessibile solamente dagli amministratori del bot.

Il pannello dovrebbe gestire i seguenti comandi **momentaneamente**: 
- /closecanteen
- /delete_files_infolder
- /bool
- /sendmessage
- /graph
- /QR_Code

**Comment by Porchetta** [comment]
Integrato.
